[workspace]
resolver = "3"
members = [
    "miniextendr-api",
    "miniextendr-macros",
    "miniextendr-engine",
    "miniextendr-bench",
    "miniextendr-lint",
    "miniextendr-cli",
]
exclude = [
    "cargo-revendor",
    "rpkg",
    "rpkg/src/rust",
    "rpkg/vendor",
    "tests/cross-package/consumer.pkg",
    "tests/cross-package/producer.pkg",
    "tests/cross-package/consumer.pkg/src/rust/",
    "tests/cross-package/producer.pkg/src/rust/",
    "tests/model_project",
    "tests/model_project/src/rust",
    "tests/model_project/vendor",
    "minirextendr",
]

[workspace.dependencies]
miniextendr-api = { version = "*", path = "miniextendr-api" }
miniextendr-macros = { version = "*", path = "miniextendr-macros" }
miniextendr-engine = { version = "*", path = "miniextendr-engine" }
linkme = "0.3"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/A2-ai/miniextendr"
keywords = ["r", "ffi", "bindings"]
categories = ["api-bindings", "external-ffi-bindings"]

[profile.release]
debug-assertions = true
