[profile.dev.build-override]
debug = false
[profile.release.build-override]
debug = false

[workspace]
members = ["rsys", "rapi", "xtask"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.70"
