[build]
rustflags = ["-Zmacro-backtrace"]
# target-dir = "target"
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32.static.posix-gcc.exe"

[env]
# LIBRSYS_LIBCLANG_INCLUDE_PATH = "${env:MINGW_ROOT}/include"
# LIBRSYS_LIBCLANG_INCLUDE_PATH = "C:/rtools42/x86_64-w64-mingw32.static.posix/include"

[alias]
xtask = "run --package xtask --"
